### ISSUE TITLE
Support for Zulu Musl on Alpine

### ISSUE THREAD

**Issue by maximann** [KoskiLabs/jdk-wrapper#27]
On linux distributions such as Alpine where musl libc is in use, it would be nice to download that JDK instead of the glibc default. This is true for distributions where musl enjoys first class support such as Zulu: https://www.azul.com/downloads/zulu/zulu-download-alpine/

Simply setting JDKW_PLATFORM inside .jdkw is not ideal since the build environment can change easily between developer machines and build environments.

**Comment by vjkoskela** [comment]
This is being addressed in #29 and will be released with `0.12.0`. Closing.
