### ISSUE TITLE
sha1sum is not available on Mac/Darwin

### ISSUE THREAD

**Issue by maximann** [KoskiLabs/jdk-wrapper#6]
[17:03:39] Resolved latest version to 0.9.2
/private/var/tmp/builder.cache/jdk/jdk-wrapper.sh: line 117: sha1sum: command not found
/private/var/tmp/builder.cache/jdk/jdk-wrapper.sh: line 117: sha1sum: command not found

Use `shasum` instead.

**Comment by vjkoskela** [comment]
This was an oversight where I missed adding cross-platform support for checksum to `jdk-wrapper.sh` while it already existed in `jdkw-impl.sh`. I've ported it over and added another fallback to `shasum` (after `sha1sum` and `md5`).

**Comment by vjkoskela** [comment]
Resolving.
